### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bendichter**

### CODE REVIEW

**Comment by h-mayorquin** [comment]
Hey, I did not think about this before.  The instructions that I have right at the end of the repo's readme imply that they have the package structure available (that is, they cloned). 

How do you envision that they run the conversions when installing from pip? 
I guess we can just point to them that a script like these two should run once they have installed the package with pip:
https://github.com/catalystneuro/murthy-lab-to-nwb/blob/main/src/murthy_lab_to_nwb/cowley2022mapping/cowley2022mapping_courtship_convert_all.py

What do you think?

**Comment by CodyCBakerPhD** [comment]
> How do you envision that they run the conversions when installing from pip?

Current policy for using the pip installation is for the instructions to point them to the usage script/examples on GitHub (or referred from the presentation) and simply instruct them to copy/paste those scripts or lines of code to a new file in whatever working directory they want to use or have access to. In that sense they wouldn't use the source scripts unless they cloned the repo (definitely not running the scripts from the install location from `site-packages`)

To be fair, they aren't locked to Python scripts (`.py`) either, they could copy/paste the code into a notebook (`.ipynb`) as well and I'm almost recommend that for first time users (heck, you can launch that in a few clicks on the DANDI hub)

**Comment by h-mayorquin** [comment]
> > How do you envision that they run the conversions when installing from pip?
> 
> Current policy for using the pip installation is for the instructions to point them to the usage script/examples on GitHub (or referred from the presentation) and simply instruct them to copy/paste those scripts or lines of code to a new file in whatever working directory they want to use or have access to. In that sense they wouldn't use the source scripts unless they cloned the repo (definitely not running the scripts from the install location from `site-packages`)
> 
> To be fair, they aren't locked to Python scripts (`.py`) either, they could copy/paste the code into a notebook (`.ipynb`) as well and I'm almost recommend that for first time users (heck, you can launch that in a few clicks on the DANDI hub)

All right, so I will add a link to the scripts that they should run in the readme installation instructions. What remains tough is the instructions that we have at the end of the readme right now:

image

Those only work if the repository was cloned. Do you think that we should keep them and just make very clear that they only work with the cloning method or should we remove them altogether to avoid any possible confusion? How do you feel?

**Comment by CodyCBakerPhD** [comment]
> Do you think that we should keep them and just make very clear that they only work with the cloning method or should we remove them altogether to avoid any possible confusion? How do you feel?

`extra_requires` to the rescue 😀 We can keep the `requirements-some-specific-experimental-setup.txt` structure nice and modular as-is, and then people could actually install from PyPI as `their-lab-to-nwb[some-specific-experimental-setup]`

**Pull request merged**
